struct Location {
    var x: Int
    var y: Int
}

let storeLocation = Location(x: 3, y: 3)

struct StoreRange {
    let center: Location
    var radius: Double
}

let areas = [
    StoreRange(center: Location(x: 3, y: 3), radius: 2.5),
    StoreRange(center: Location(x: 8, y: 8), radius: 2.5)
]

func distance(from source: (x: Int, y: Int), to target: (x: Int, y: Int)) -> Double {
    let distanceX = Double(source.x - target.x)
    let distanceY = Double(source.y - target.y)
    return (distanceX * distanceX + distanceY * distanceY).squareRoot()
}

func isInStoreRange(_ location: Location) -> Bool {
    for area in areas {
        let distanceToStore = distance(from: (area.center.x, area.center.y), to: (location.x, location.y))
        if distanceToStore < area.radius {
            return true
        }
    }
    return false
}

struct Customer {
    var firstName: String
    var lastName: String
    var eMail: String
    var phoneNumber: String //setting as sting as we haven't learned regular expressions yet
    var Newsletter: Bool
    var location: Location
    
    func wantsNewsletter() -> Bool {
        return Newsletter
    }
}

//all names and phone numbers randomly generated by chatGPT - these are *NOT* real people
var customers: [Customer] = []
var cust = Customer(firstName: "Samantha", lastName: "Evergreen", eMail: "SEvergreen@Qmail.com", phoneNumber: "(905)555-0101", Newsletter: true, location: Location(x: 3, y: 2))
customers.append(cust)

cust = Customer(firstName: "Marcus", lastName: "Hawthorne", eMail: "MHawthorne@Qmail.com", phoneNumber: "(905)555-2323", Newsletter: false, location: Location(x: 8, y: 5))
customers.append(cust)

cust = Customer(firstName: "Lily", lastName: "Winterborne", eMail: "LWinterborne@Qmail.com", phoneNumber: "(905)555-4545", Newsletter: false, location: Location(x: 5, y: 7))
customers.append(cust)

cust = Customer(firstName: "Oliver", lastName: "Sterling", eMail: "ESterling@Qmail.com", phoneNumber: "(905)555-6767", Newsletter: true, location: Location(x: 2, y: 6))
customers.append(cust)

cust = Customer(firstName: "Emily", lastName: "Crestwood", eMail: "ECrestwood@Qmail.com", phoneNumber: "(905)555-8989", Newsletter: true, location: Location(x: 9, y: 3))
customers.append(cust)

cust = Customer(firstName: "Nathan", lastName: "Blackwood", eMail: "NBlackwood@Qmail.com", phoneNumber: "(905)555-1212", Newsletter: false, location: Location(x: 6, y: 4))
customers.append(cust)

cust = Customer(firstName: "Isabella", lastName: "Fairfax", eMail: "IFairfax@Qmail.com", phoneNumber: "(905)555-3434", Newsletter: true, location: Location(x: 4, y: 9))
customers.append(cust)

cust = Customer(firstName: "Benjamin", lastName: "Alderwood", eMail: "BAlderwood@Qmail.com", phoneNumber: "(905)555-5656", Newsletter: true, location: Location(x: 10, y: 8))
customers.append(cust)

cust = Customer(firstName: "Sophia", lastName: "Rivers", eMail: "SRivers@Qmail.com", phoneNumber: "(905)555-7878", Newsletter: false, location: Location(x: 1, y: 1))
customers.append(cust)

cust = Customer(firstName: "Jackson", lastName: "Whitmore", eMail: "JWhitmore@Qmail.com", phoneNumber: "(905)555-9999", Newsletter: true, location: Location(x: 7, y: 6))
customers.append(cust)

func printCustomersWithinStoreRange(storeLocation: Location, customers: [Customer]) {
    for customer in customers {
        if isInStoreRange(customer.location) {
            print(customer.eMail)
        }
    }
}



